# Generated by Django 3.1.1 on 2020-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0003_auto_20200917_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
